import pandas

df = pandas.read_csv('C:/Users/dirce/Downloads/wine_dataset.csv')

print(' ')
print('\033[1:33mColunas 0 a 4\033[m')
print(df.iloc[:, 0:5].head())
print(' ')
print('\033[1:33mColunas 5 a 9\033[m')
print(df.iloc[:, 5:10].head())
print(' ')
print('\033[1:33mColunas 10 a 13\033[m')
print(df.iloc[:, 10:13].head())
print(' ')
print('\033[1:33mTotal de Linhas e Colunas\033[m')
print(df.shape)
print(' ')
print('\033[1:33mQuantas vezes se repete cada teor alcoolico\033[m')
print(df['alcohol'].value_counts())
print(' ')
print('\033[1:33mProcurando palavra tenha qualquer coisa na frente e ao final de \'ed\'\033[m')
print(df.filter(regex='.ed.'))
print(' ')
df['style'] = df['style'].replace('red', 1)
nf = df[((df['quality'] == 7) & (df['style'] == 1))][['residual_sugar', 'alcohol']]
print('\033[1:33mBebidas classificadas com maior qualidade entre os vinhos tintos\033[m')
print(nf)
print(' ')
print('\033[1:33mCount = Soma , Mean = Média , Std = Desvio Padrão , e Porcentagens\033[m')
print(nf.describe())
print(' ')
df['style'] = df['style'].replace(1, 'red')
filtro = df[['style', 'alcohol']].groupby(['style']).mean()
print('\033[1:33mMédia de teor alcólico de cada tipo de vinho\033[m')
print(filtro)
print(' ')
filtro = df[['style', 'quality', 'residual_sugar', 'alcohol']].groupby(['style', 'quality']).mean()
print('\033[1:33mMédia de teor alcólico e açucar de cada tipo de vinho por sua qualidade\033[m')
print(filtro)